In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense

from tensorflow.keras.datasets import mnist

In [2]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

# Introduction to Deep Learning - Basic Models Demo
---

In [3]:
a = 5
b = 8

result = (2 * a + 3 * b) ** 2

print(result)
print(type(result))

1156
<class 'int'>


In [4]:
a = np.array([5, 1, 2, 3, 10])
b = np.array([8, -3, 8, 15, 0])

result = (2 * a + 3 * b) ** 2

print(result)
print(type(result))

[1156   49  784 2601  400]
<class 'numpy.ndarray'>


In [5]:
a = tf.constant([5, 1, 2, 3, 10])
b = tf.constant([8, -3, 8, 15, 0])

result = (2 * a + 3 * b) ** 2

print(result)
print(type(result))

tf.Tensor([1156   49  784 2601  400], shape=(5,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [6]:
a = tf.constant(np.array([5, 1, 2, 3, 10]))
b = tf.constant(np.array([8, -3, 8, 15, 0]))

result = (2 * a + 3 * b) ** 2

print(result)
print(type(result))

tf.Tensor([1156   49  784 2601  400], shape=(5,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [7]:
a = tf.constant(5)
b = tf.constant(8)

result = (2 * a + 3 * b) ** 2

print(result)
print(type(result))

tf.Tensor(1156, shape=(), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [8]:
a = 5
b = 8

tf.pow(tf.add(tf.multiply(2, a), tf.multiply(3, b)), 2).numpy()

1156

In [9]:
tf.reduce_mean(np.random.uniform(size=(10, 10)))

<tf.Tensor: shape=(), dtype=float64, numpy=0.46575619612310065>

In [10]:
tf.keras.backend.clear_session()

## Adult Income Data

In [11]:
income_data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data', header=None, engine="python", sep=", ")
income_data.columns = ["age", "workclass", "fnlwgt", "education", "education-num", "material-status", "occupation", "relationship", "race", "sex", "capital-gain", "capital-loss", "hours-per-week", "native-country", "income_class"]

income_data

age         workclass  fnlwgt   education  education-num  \
0       39         State-gov   77516   Bachelors             13   
1       50  Self-emp-not-inc   83311   Bachelors             13   
2       38           Private  215646     HS-grad              9   
3       53           Private  234721        11th              7   
4       28           Private  338409   Bachelors             13   
...    ...               ...     ...         ...            ...   
32556   27           Private  257302  Assoc-acdm             12   
32557   40           Private  154374     HS-grad              9   
32558   58           Private  151910     HS-grad              9   
32559   22           Private  201490     HS-grad              9   
32560   52      Self-emp-inc  287927     HS-grad              9   

          material-status         occupation   relationship   race     sex  \
0           Never-married       Adm-clerical  Not-in-family  White    Male   
1      Married-civ-spouse    Exec-managerial        Husband  White    Male   
2                Divorced  Handlers-cleaners  Not-in-family  White    Male   
3      Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4      Married-civ-spouse     Prof-specialty           Wife  Black  Female   
...                   ...                ...            ...    ...     ...   
32556  Married-civ-spouse       Tech-support           Wife  White  Female   
32557  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
32558             Widowed       Adm-clerical      Unmarried  White  Female   
32559       Never-married       Adm-clerical      Own-child  White    Male   
32560  Married-civ-spouse    Exec-managerial           Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country income_class  
0              2174             0              40  United-States        <=50K  
1                 0             0              13  United-States        <=50K  
2                 0             0              40  United-States        <=50K  
3                 0             0              40  United-States        <=50K  
4                 0             0              40           Cuba        <=50K  
...             ...           ...             ...            ...          ...  
32556             0             0              38  United-States        <=50K  
32557             0             0              40  United-States         >50K  
32558             0             0              40  United-States        <=50K  
32559             0             0              20  United-States        <=50K  
32560         15024             0              40  United-States         >50K  

[32561 rows x 15 columns]

In [12]:
income_classes = income_data["income_class"]
income_attributes = income_data.drop(columns=["income_class"])

In [13]:
income_attributes = income_attributes.drop(columns=["fnlwgt"])

In [14]:
income_classes = income_classes.replace({"<=50K": 0, ">50K": 1})

C:\Users\BOEVVBOY\AppData\Local\Temp\ipykernel_13832\959202074.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  income_classes = income_classes.replace({"<=50K": 0, ">50K": 1})


In [15]:
income_attributes = pd.get_dummies(income_attributes)

In [16]:
income_attributes_train, income_attributes_test, income_classes_train, income_classes_test = train_test_split(
    income_attributes,
    income_classes,
    test_size=5000, 
    stratify=income_classes
)
income_attributes_train.shape, income_attributes_test.shape, income_classes_train.shape, income_classes_test.shape

((27561, 107), (5000, 107), (27561,), (5000,))

In [25]:
scalar = MinMaxScaler()
income_attributes_train_scaled = scalar.fit_transform(income_attributes_train)
income_attributes_test_scaled = scalar.transform(income_attributes_test)

In [18]:
print(income_attributes_train)

       age  education-num  capital-gain  capital-loss  hours-per-week  \
7099    30             15             0             0              50   
7109    34              9             0             0              40   
23859   25             13          3325             0              40   
25038   27             13             0             0              40   
13670   43              9             0             0              40   
...    ...            ...           ...           ...             ...   
25548   51             11             0             0              50   
4875    49             14             0             0              50   
25371   32             10             0             0              36   
32242   33              9             0             0              35   
22267   47              9             0             0              46   

       workclass_?  workclass_Federal-gov  workclass_Local-gov  \
7099         False                  False                

In [19]:
print(income_classes_train)

7099     0
7109     0
23859    0
25038    0
13670    0
        ..
25548    1
4875     1
25371    0
32242    0
22267    0
Name: income_class, Length: 27561, dtype: int64


In [26]:
num_attributes = income_attributes.shape[1]
num_attributes

107

In [39]:
logistic_regression = Sequential([
    Input(shape = (num_attributes,)),
    Dense(1, activation = "sigmoid")
])

logistic_regression.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_11 (Dense)                     │ (None, 1)                   │             108 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 108 (432.00 B)

 Trainable params: 108 (432.00 B)

 Non-trainable params: 0 (0.00 B)

In [31]:
logistic_regression.compile(
    loss="binary_crossentropy",
    optimizer="sgd"
)

In [36]:
logistic_regression.fit(income_attributes_train_scaled, income_classes_train, epochs=100)

Epoch 1/100
862/862 ━━━━━━━━━━━━━━━━━━━━ 1s 868us/step - loss: 0.4903
Epoch 2/100
862/862 ━━━━━━━━━━━━━━━━━━━━ 1s 802us/step - loss: 0.4308
Epoch 3/100
862/862 ━━━━━━━━━━━━━━━━━━━━ 1s 769us/step - loss: 0.4063
Epoch 4/100
862/862 ━━━━━━━━━━━━━━━━━━━━ 1s 791us/step - loss: 0.3970
Epoch 5/100
862/862 ━━━━━━━━━━━━━━━━━━━━ 1s 803us/step - loss: 0.3912
Epoch 6/100
862/862 ━━━━━━━━━━━━━━━━━━━━ 1s 755us/step - loss: 0.3840
Epoch 7/100
862/862 ━━━━━━━━━━━━━━━━━━━━ 1s 779us/step - loss: 0.3811
Epoch 8/100
862/862 ━━━━━━━━━━━━━━━━━━━━ 1s 766us/step - loss: 0.3808
Epoch 9/100
862/862 ━━━━━━━━━━━━━━━━━━━━ 1s 807us/step - loss: 0.3755
Epoch 10/100
862/862 ━━━━━━━━━━━━━━━━━━━━ 1s 774us/step - loss: 0.3745
Epoch 11/100
862/862 ━━━━━━━━━━━━━━━━━━━━ 1s 758us/step - loss: 0.3712
Epoch 12/100
862/862 ━━━━━━━━━━━━━━━━━━━━ 1s 792us/step - loss: 0.3744
Epoch 13/100
862/862 ━━━━━━━━━━━━━━━━━━━━ 1s 833us/step - loss: 0.3692
Epoch 14/100
862/862 ━━━━━━━━━━━━━━━━━━━━ 1s 747us/step - loss: 0.3697
Epoch 15/100
86

In [46]:
nn = Sequential([
    Input(shape = (num_attributes,)),


    Dense(30, activation = "relu"),
    Dense(20, activation = "relu"),
    Dense(10, activation = "relu"),
    
    Dense(1, activation = "sigmoid")
])
nn.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_16 (Dense)                     │ (None, 30)                  │           3,240 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_17 (Dense)                     │ (None, 20)                  │             620 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_18 (Dense)                     │ (None, 10)                  │             210 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_19 (Dense)                     │ (None, 1)                   │              11 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 4,081 (15.94 KB)

 Trainable params: 4,081 (15.94 KB)

 Non-trainable params: 0 (0.00 B)

In [50]:
nn.compile(
    loss="binary_crossentropy",
    optimizer="sgd",
    metrics=[
        "accuracy",
        tf.keras.metrics.Precision(),
        tf.keras.metrics.Recall()
    ]
)

In [51]:
nn.fit(income_attributes_train_scaled, income_classes_train, epochs=10)

Epoch 1/10
862/862 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.7598 - loss: 0.5473 - precision_3: 0.5481 - recall_1: 0.0459
Epoch 2/10
862/862 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8154 - loss: 0.4012 - precision_3: 0.6818 - recall_1: 0.4331
Epoch 3/10
862/862 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8265 - loss: 0.3760 - precision_3: 0.6907 - recall_1: 0.5081
Epoch 4/10
862/862 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8299 - loss: 0.3649 - precision_3: 0.6926 - recall_1: 0.5173
Epoch 5/10
862/862 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8322 - loss: 0.3569 - precision_3: 0.6983 - recall_1: 0.5463
Epoch 6/10
862/862 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8347 - loss: 0.3510 - precision_3: 0.7037 - recall_1: 0.5565
Epoch 7/10
862/862 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8328 - loss: 0.3502 - precision_3: 0.6933 - recall_1: 0.5512
Epoch 8/10
862/862 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8350 - loss: 0.3475 - precision_3: 0.7002 - r

In [52]:
nn.evaluate(income_attributes_train_scaled, income_classes_train)

862/862 ━━━━━━━━━━━━━━━━━━━━ 1s 902us/step - accuracy: 0.8438 - loss: 0.3344 - precision_3: 0.7383 - recall_1: 0.5450


[0.3378865420818329,
 0.8404629826545715,
 0.7272727489471436,
 0.5400030016899109]

In [53]:
nn.evaluate(income_attributes_test_scaled, income_classes_test)

157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8488 - loss: 0.3337 - precision_3: 0.7324 - recall_1: 0.5675


[0.3394550681114197, 0.8416000008583069, 0.733031690120697, 0.5382059812545776]